[package]
name = "forkserver_slopt"
version = "0.15.3"
authors = ["matheusbaptistella <mbapts@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
opt-level = 3

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
env_logger = "0.11.5"
libafl = { path = "../../../libafl", features = ["std", "derive"] }
libafl_bolts = { path = "../../../libafl_bolts" }
log = { version = "0.4.22", features = ["release_max_level_info"] }
nix = { version = "0.29.0", features = ["signal"] }
serde = "1.0.219"
rand_distr = "0.5.1"
rand = "0.9.2"

[[bin]]
name = "afl-fuzz"
path = "src/bin/afl-fuzz.rs"

[[bin]]
name = "afl-fuzz-adsts"
path = "src/bin/afl-fuzz-adsts.rs"

[[bin]]
name = "afl-fuzz-dbe"
path = "src/bin/afl-fuzz-dbe.rs"

[[bin]]
name = "afl-fuzz-dts"
path = "src/bin/afl-fuzz-dts.rs"

[[bin]]
name = "afl-fuzz-expix"
path = "src/bin/afl-fuzz-expix.rs"

[[bin]]
name = "afl-fuzz-exppp"
path = "src/bin/afl-fuzz-exppp.rs"

[[bin]]
name = "afl-fuzz-klucb"
path = "src/bin/afl-fuzz-klucb.rs"

[[bin]]
name = "afl-fuzz-ts"
path = "src/bin/afl-fuzz-ts.rs"

[[bin]]
name = "afl-fuzz-ucb"
path = "src/bin/afl-fuzz-ucb.rs"
